public with sharing class Wizardpage {
    Account acc=new Account();
    public Account getAcc() {
        return Acc;
    }


    public PageReference Save() {
        return null;
    }


    public PageReference Firstpage() {
        return page.P1;
    }


    public PageReference Thirdpage() {
        return page.P3;
    }


    public PageReference Secondpage() {
        return page.P2;
    }

}